<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h3>Notícias</h3>

<ul>
<?php
foreach($data['news'] as $new) {
    echo "<li><a href='noticias/{$new['id']}'>{$new['titulo']}</a></li>";
}
?>
</ul>
</body>
</html>
